### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mdwagner** [luckyframework/lucky_env#27]
From what I can tell, as of this [commit](https://github.com/luckyframework/lucky_env/commit/4d596010ec6804cc86cbdba00b187cf4ab378aaf) (latest), Windows is supported and working on **Crystal 1.7.1**. Ameba, however, does not seem to support windows yet, or at least I can't run `shards install` for it successfully.

I guess the least we can do is just add Windows in a Github Action to validate it compiles and runs.

**Comment by jwoertink** [comment]
Yeah, would be nice to start getting these smaller shards out of the way sooner. Hopefully it doesn't take a ton of effort.
