### ISSUE TITLE
Don't parse correct for ENV which value is another defined env?

### ISSUE THREAD

**Issue by zw963** [luckyframework/lucky_env#30]
Following ENV not work as expected.

```
# .env
APP_PORT=3000
APP_NAME=production_line_report
LUCKY_ENV=development
DB_HOST=localhost
DB_PORT=5432
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_NAME=${APP_NAME}_${LUCKY_ENV}
```

the expected DB_NAME is product_line_report_development, but the actually is: ``${APP_NAME}_${LUCKY_ENV}``.

If `source ~/.env` use bash shell,  the result is expected.

So, i consider we should support this, give the user the least surprise

**Comment by zw963** [comment]
I create a PR for fix this. #31

**Comment by jwoertink** [comment]
I actually would never expect this to work. I've never seen this sort of interpolation in a `.env` file before. I do like the change, but I also want to be clear that this shard is not intended to be a bash-like ENV loader. This shard will eventually change https://github.com/luckyframework/lucky_env/issues/1 to be very specific to Lucky's needs. 

But for now, I think this is a nice change and we can add it in :+1:
