### ISSUE TITLE
Add an overload that doesn't blow up with there's no .env

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_env#5]
I think the default should always be to blow up when there's no .env because default Lucky apps require some ENV to be set. However, you may not be using this in a Lucky project. Maybe it's in a shard, or only being used for testing? In this case, it would be nice to have a separate `load` overload that just returns `nil` if the `.env` file it needs doesn't exist. This would basically be an escape hatch.

**Comment by stephendolan** [comment]
This will still be important for Lucky apps since for deployments like Heroku, you generally use their built-in ENV manager rather than a file. Same thing for render.com as well!

For now it's easy enough to use `LuckyEnv.load(".env") if Lucky::Env.development?`, though!
